services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "${OLLAMA_PORT}:11434"
    environment:
      - OLLAMA_KEEP_ALIVE=-1
    volumes:
      - "${MODEL_PATH}:/root/.ollama"
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

    healthcheck:
      test: ["CMD", "ollama", "--version"]
      interval: 30s
      timeout: 10s
      retries: 5
    entrypoint: >
      /bin/sh -c "
      ollama pull ${LLM} &
      ollama pull ${ENCODER_MODEL} &
      ollama serve
      "

  text-spellcheck:
      image: cr.weaviate.io/semitechnologies/text-spellcheck-model:pyspellchecker-en

  weaviate:
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8080'
    - --scheme
    - http
    image: semitechnologies/weaviate
    ports:
    - ${WEAVIATE_PORT}:8080
    volumes:
    - ${DB_PATH}:/var/lib/weaviate
    restart: on-failure:0
    environment:
      SPELLCHECK_INFERENCE_API: 'http://text-spellcheck:8080'
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'text2vec-ollama'
      ENABLE_MODULES: 'text2vec-ollama,text-spellcheck,generative-ollama'
      CLUSTER_HOSTNAME: 'node1'
    depends_on:
      ollama:
        condition: service_healthy

networks:
  default:
    name: app_network
